server {
    listen 443 ssl;
    http2 on;
    server_name $PROGET_APP_INTRA_PATH $PROGET_APP_PUBLIC_PATH;

    access_log /var/log/nginx/proget_access.log combined;
    error_log /var/log/nginx/proget_error.log debug;

    location / {
        proxy_pass http://$PROGET_CONTAINER_NAME:80;
        
        include /etc/nginx/conf.d/use-default-headers.inc;
        include /etc/nginx/conf.d/use-default-timeouts.inc;
    }

    include /etc/nginx/conf.d/use-healthcheck.inc;
}
