version = 5.6.0
archive_dir = /etc/letsencrypt/archive/jbdesign.com.br
cert = /etc/letsencrypt/live/jbdesign.com.br/cert.pem
privkey = /etc/letsencrypt/live/jbdesign.com.br/privkey.pem
chain = /etc/letsencrypt/live/jbdesign.com.br/chain.pem
fullchain = /etc/letsencrypt/live/jbdesign.com.br/fullchain.pem
[renewalparams]
account = ebcae3f232996566030cdf54bf6e8b19
pref_challs = dns-01,
authenticator = manual
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
